language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vladhot/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vladhot/docker-react npm run test -- --coverage
